name: Build

concurrency:
  group: "build"
  cancel-in-progress: true

on:
  workflow_dispatch:
  #push:
    #branches:
     # - master
     # - main
   # paths-ignore:
     # - '*.md'
     # - '*.png'
     # - '*.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "src"

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: "builds"
          path: "builds"
      
      - name: Clean old builds
        run: rm $GITHUB_WORKSPACE/builds/*.cs3 || true

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17
          cache: gradle  # IMPORTANTE: cache gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2

      - name: Access Secrets
        env:
          TMDB_API: ${{ secrets.TMDB_API }}
        run: |
          cd $GITHUB_WORKSPACE/src
          echo TMDB_API=$TMDB_API >> secrets.properties  # RESTA secrets.properties

      - name: Clean Gradle Cache (Optional)
        run: |
          cd $GITHUB_WORKSPACE/src
          rm -rf ~/.gradle/caches/transforms-*/* || true
          rm -rf ~/.gradle/caches/modules-2/files-2.1/com.lagradost/* || true
          
      - name: Build Plugins
        timeout-minutes: 15
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          # PRIMA prova senza timeout per debugging
          ./gradlew clean
          ./gradlew make makePluginsJson ensureJarCompatibility --stacktrace --info
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || exit 0
          git push --force
